name: Recovery Build

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3 # Required to mount the Github Workspace to a volume
    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image: ghcr.io/sushrut1101/docker:arch
        shell: bash
        run: |
          git clone https://github.com/mmtrt/OrangeFox-CI
          cd OrangeFox-CI ; ls -al ; chmod +x scripts/*.sh ; chmod +x *.sh
          echo $PWD
          export FOX_SYNC=https://gitlab.com/OrangeFox/sync.git
          export CONFIG=/root/OrangeFox-CI/config.sh
          source config.sh
          bash scripts/checks.sh
          bash scripts/sync.sh
          bash scripts/build.sh
          bash scripts/upload.sh
